# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Debug'

steps:

- task: DockerInstaller@0 
  displayName: Docker Installer ğŸ“¦
  inputs:
    dockerVersion: '17.09.0-ce'

- task: CmdLine@2
  displayName: Docker login ğŸ
  inputs:
    script: 'docker login -u 542153354 -p $(DockerPassword)'

- task: CmdLine@2
  displayName: install sshpass
  inputs:
    script: |
      sudo apt-get install sshpass

- task: Docker@2
  displayName: Docker build
  inputs:
    command: 'build'
    Dockerfile: '**/AntDesign.Docs.Wasm/Dockerfile'
    arguments: '-t 542153354/antdesign.docs.wasm:v1.0'

- task: CmdLine@2
  displayName: Docker push
  inputs:
    script: 'docker push 542153354/antdesign.docs.wasm:v1.0'

- task: CmdLine@2
  displayName: deploy to TencentCloud ğŸš€
  inputs:
    script: |
      sshpass -p "$(TencentCloudPassword)" ssh -o StrictHostKeyChecking=no -t -t ubuntu@$(TencentCloudIP) bash -s < deploy.sh